name: Run Vitest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Repository klonen
        uses: actions/checkout@v3

      - name: 🟢 Node.js installieren (v22)
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 📦 Abhängigkeiten installieren
        run: npm install

      # Optional: Projekt-Build (auskommentiert)
      # - name: 🛠 Projekt bauen
      #   run: npm run build

      - name: 🧪 Vitest Tests ausführen
        run: npx vitest run


